Infinite heroes
KrillOrBeKrilled/GMTK-2023 pull request #27
Opened 2023-09-07 21:16 UTC by eon704

2023-09-09 21:10 UTC, Eryngii01 commented on Assets/Code/Scripts/Managers/GameManager.cs
> +      this._levelData.WavesData.WavesList.RemoveAt(0);
This may be costly to do with a List instead of a Queue if the number of waves gets to be very large for a level since RemoveAt(0) shifts everything in the List after removal.

If we don't plan on making extensive levels with a lot of waves, then this shouldn't make much of a difference!

2023-09-09 21:39 UTC, Eryngii01 requested changes
Great work! I love the addition of the FindMissingReferences and level loading with interchangeable scriptable objects to be able to reuse the same scene with different wave and hero data to easily reuse resources! Hero waves are splendid and kind of scary! 😆 

A few things I would like to address, but most are just nitpicks on my end so some don't necessarily have to be changed:
- The map UI is rendered above the dialogue text boxes, so Dogan's welcoming dialogue is a little obscured
- The hen icon can go past the map UI slider if the player flies too far, but we can address this later if we plan on enforcing level boundaries
- The Trap Icon tints do not apply until a coin is earned for the first time
- Player movement is still possible when the game over UI for defeating all heroes appears on the screen
- If you play the tutorial dialogue, you would have to fight one extra hero until the remaining ones spawn from the wave data. This may introduce a disadvantage, especially if coins are made to be a scarce resource
- I'm worried that hero waves may become overwhelming for players if waves are spawned at an interval instead of by completing the previous wave...This may penalize players that take time developing thorough strategies and/or build traps further in the level...We can always address this later in another update after further design discussions!
- It may be expensive memory-wise (depending on how many heroes we have on the map at a single time) to have each hero clone and player store its own reference to the level start and end Transforms to calculate the map position in a getter; maybe we could consider having the calculations take place on Update in MapUI and store the level start and end positions there?

2023-09-10 04:22 UTC, eon704 commented
Thank you for closely reviewing this PR!

## Will be fixed in this PR:
- The map UI is rendered above the dialogue text boxes, so Dogan's welcoming dialogue is a little obscured.
- The hen icon can go past the map UI slider if the player flies too far, but we can address this later if we plan on enforcing level boundaries.
- If you play the tutorial dialogue, you would have to fight one extra hero until the remaining ones spawn from the wave data. This may introduce a disadvantage, especially if coins are made to be a scarce resource.
- Player movement is still possible when the game over UI for defeating all heroes appears on the screen
- It may be expensive memory-wise (depending on how many heroes we have on the map at a single time) to have each hero clone and player store its own reference to the level start and end Transforms to calculate the map position in a getter; maybe we could consider having the calculations take place on Update in MapUI and store the level start and end positions there?
  - Good catch! Will fix those 👌 

## Can be addressed later after discussion:
- I'm worried that hero waves may become overwhelming for players if waves are spawned at an interval instead of by completing the previous wave...This may penalize players that take time developing thorough strategies and/or build traps further in the level...We can always address this later in another update after further design discussions!
  - This can be disabled by setting the interval until the next wave to `-1` (any negative number will do 😅)! Just decided to put that in for now, if we decide that we want all waves to come only after the current one was eliminated we can remove that 👌

## Will be fixed in the following PRs:
- The Trap Icon tints do not apply until a coin is earned for the first time
  - Old bug, would be better to dedicate a small PR to it 👍

2023-09-10 15:22 UTC, Eryngii01 commented
I see, I didn't catch the `-1` interval for the next wave before, but it sounds like a good idea to keep it in for flexibility with level design as we change things up going forward!

2023-09-10 15:49 UTC, Eryngii01 commented
Thank you for adding the fixes! They work well now! 🙏 

Unfortunately after testing again, I have some more issues to bring up here 😅 
- The dialogue speech bubbles appear to render over the pause menu when you pause the game
- The coin earning coroutine still runs when the game is over. This isn't game-breaking and appears to be an old issue on main so we can always address this later
- The `WaveSpawnCoroutine` reference is null, throwing a null reference error when the player dies from contact with the hero spawned in the tutorial dialogue. Otherwise, this issue doesn't show up anytime else since the `WaveSpawnCoroutine` has already been started

2023-09-11 04:43 UTC, eon704 commented
- After taking a deeper look into dialogue speech bubbles it will take quite a bit of work to fix that. Turns out it is on a separate canvas 😢
- Yeah, looks like the coin coroutine is quite old, will fix it in another PR.
- Thank you for catching the `WaveSpawnCoroutine` null error, missed that one!

2023-09-11 06:23 UTC, eon704 commented on Assets/Code/Scripts/Managers/GameManager.cs
> +      this._levelData.WavesData.WavesList.RemoveAt(0);
Switched to Queue!

2023-09-11 06:35 UTC, eon704 commented
Alright, fixed the `WaveSpawnCoroutine` nullRef error!
For other bugs, let's fix them in different PRs since this one is already quite large 😅

2023-09-11 16:31 UTC, Eryngii01 approved these changes
The updates work well! I'll add the tickets to the Trello for future updates 👌

2023-09-11 21:40 UTC, merged