Basic Hero AI - Idle, Run, Jump
KrillOrBeKrilled/GMTK-2023 pull request #39
Opened 2023-11-05 05:06 UTC by Eryngii01

## Changes:
- Implemented basic Behaviour Tree scripts, along with certain composite and decorator nodes such as: `Parallel`, `RandomSequence`, `RandomSelector`, `Sequence`, `Selector`, `Inverter`, and `Succeeder`
- Implemented a `BasicBT` that covers the idle, run, and jump behaviours: The jump nodes have higher priority, followed by the `Run` node and `Idle` node.
- Transferred `HeroMovement` logic to the BasicBT
- Updated the hero AI to remove the need for jumppads:
1. Implemented a `FieldOfView` for the hero, which draws a wedge area at runtime in the scene view and updates it when any obstacles or pits are sighted for debugging purposes. The `FoV` contains methods for finding pits and finding obstacles all within the FoV area.
2. The finding a pit method in `FoV` is slightly nuanced; it will first check that a raycast has in fact detected a ledge. If a ledge is found, it will first proceed to look above where the ground was sighted as far as the FoV area allows. After looking through all the target platforms, it will only select the closest one to serve as a final jump land point option. But if any platforms are directly above the detected ledge, it will perceive this as a ceiling and stop searching upwards any further. It's similar for the checks below the detected ledge, except all platforms will be accepted with priority to the closer ones. Once the ground is detected at the tile directly to the right of the ledge and further down the pit, it will be deduced as the bottom of the pit and abort any further searching. The pit bottom will only be accepted as a viable landing position if there is not trap present and the platform is wide enough to safely land.
3. Jump logic is set up as the following: `LookForGround` AND (`Fall` OR (`LookForObstacle` AND `ApproachTarget` AND `DecideJumpForce` AND `Jump`))
4. `LookForGround` is always called on update (hero is always looking for the ground even midair) and always returns `SUCCESS`. It contains a sorted list of jump actions `<Vector3, Vector3>` as jump launch position and jump land position pairs, ordered by the horizontal distance from the hero (with the shortest distance at the front of the list). Every frame, it checks if the first entry of the list of registered jump actions is already passed by the hero and removes it if so.
5. After checking the list contents, `LookForGround` then looks for a pit through `FoV`. If a pit is found, it will gauge the options of potential jump landing points and choose an option accordingly (for now it's at random) and then register it as a jump action.  Note that it is possible to get jump actions with no target land positions if nothing is found within the FoV area. In this case, it's up to the node logic to decide what to do when that happens. (What would a person do if they see the edge of a cliff and nowhere else to go?)
6. If a pit is not detected, the hero will try to look for a wall ahead of them and register a jump action for that. Jump actions will be registered in an ordered matter in the sorted list.
7. `Fall` will be executed next and will just basically check whether the hero is grounded or not. If the hero is midair, it will return `SUCCESS` and will not proceed to the jump logic. Otherwise, the jump logic will be executed.
8. `LookForObstacle` will check that a jump action is available and will set the necessary data needed further on in the sequence. It will always check to see if any new action is recorded to be closer than the current jump launch point and update the data. It will return `FAILURE` if there is no jump action to be had.
9. `ApproachTarget` will make the hero run towards the jump launch point at a set quickened dash speed, and if it reaches the launch point, it will proceed further in the sequence. If the hero passes the target for whatever reason, this node will return `FAILURE` and stop the jump process in its tracks.
10. `DecideJumpForce` will calculate the required jump force to successfully make the jump from the launch point to the jump land point and will always return `SUCCESS`.
11. `Jump` will finalize the jump by applying the velocity to the rigidbody and plays all associated animations and SFX.

## Updated files:
- GameManager
- Hero
- HeroMovement
- Added AI and BehaviourTree folders

## Recording:
N/A (More to come!)

2023-11-17 07:45 UTC, eon704 commented on Assets/Code/Scripts/Heroes/BehaviourTree/Composites/RandomSelector.cs
> +                var node = nodes[Random.Range(0, nodes.Count - 1)];
Just a quick note, `Random.Range(a, b)` returns a random value in the range [a, b).
In this case, the nodes that are last in the list will be excluded from the Random choice

2023-11-17 07:46 UTC, eon704 commented on Assets/Code/Scripts/Heroes/BehaviourTree/Composites/RandomSequence.cs
> +                var node = nodes[Random.Range(0, nodes.Count - 1)];
Same here 😅

2023-11-17 07:52 UTC, eon704 commented on Assets/Code/Scripts/Heroes/BehaviourTree/Decorators/Repeater.cs
> +using System.Collections;
The file seems to only contain default Unity parts and must be unused in `Hero AI`, leaving a comment here just so that it comes to attention 👌

2023-11-17 08:16 UTC, eon704 commented on Assets/Code/Scripts/Heroes/FieldOfView.cs
> +            Gizmos.matrix = Handles.matrix = transform.localToWorldMatrix;
This method will need to be encapsulated within a 
```
#if UNITY_EDITOR 
  ...
#endif
``` 
macro since the `Handles` class is only available inside the Unity Editor. 
The project will fail during the build if left as is 😅 

(Slightly annoying Unity thing, learned it painfully during one of the game jams when needed to quickly make a build for submission 🥲)

2023-11-17 08:34 UTC, eon704 commented on Assets/Code/Scripts/Heroes/AI/Basic/Tasks/ApproachTarget.cs
> +                case true when isHeroOnPlatform:
Didn't know you could use a `switch` statement like that, pretty cool!

2023-11-17 08:48 UTC, eon704 commented on Assets/Code/Scripts/Heroes/AI/Basic/Checks/DecideJumpForce.cs
> +                Debug.LogError("Hero cannot find a target platform!");
Since this is kind of an expected behaviour at this point, do we still to log an `Error` in this case?
Perhaps we could lower it to a `Warning` instead? 😅

2023-11-17 08:59 UTC, eon704 commented
I finished reviewing the code, and only a few minor things that need to be changed here and there. 
Overall very impressive work! The AI is quite complex but still easy to understand from the logic point.

On a side note, I didn't review the math part quite as carefully. It does seem to be quite in-depth, with a decent amount of Linear algebra of matrix multiplications or a good chunk of `Vector3` calculations 😅 
I will trust the math equations are correct, won't be checking them in detail 👌😅 

Will review the other parts of the PR such as scenes and prefabs tomorrow.

2023-11-18 00:02 UTC, eon704 commented on Assets/Prefabs/Traps/TestTrap1.prefab
Not necessary for this PR.

I think at this point it is safe to delete the test traps together with their scripts?

2023-11-18 00:06 UTC, eon704 requested changes
Amazing work! Having all the necessary BT infrastructure set up is huge and opens so many doors in making them even more fun adversaries!

Some minor adjustments here and there, and then the PR will good to go! 🚀

2023-11-18 05:26 UTC, Eryngii01 commented on Assets/Code/Scripts/Heroes/BehaviourTree/Composites/RandomSelector.cs
> +                var node = nodes[Random.Range(0, nodes.Count - 1)];
Oh, thanks for pointing that out! I didn't realize `Random.Range` works that way

2023-11-18 05:33 UTC, Eryngii01 commented on Assets/Code/Scripts/Heroes/BehaviourTree/Composites/RandomSelector.cs
> +                var node = nodes[Random.Range(0, nodes.Count - 1)];
Ah, I think I mixed it up with `Random.Range` that returns a float. I'll watch out for that next time! 👀

2023-11-18 05:35 UTC, Eryngii01 commented on Assets/Code/Scripts/Heroes/BehaviourTree/Composites/RandomSelector.cs
> +                var node = nodes[Random.Range(0, nodes.Count - 1)];
Fixed!

2023-11-18 05:35 UTC, Eryngii01 commented on Assets/Code/Scripts/Heroes/BehaviourTree/Composites/RandomSequence.cs
> +                var node = nodes[Random.Range(0, nodes.Count - 1)];
Fixed!

2023-11-18 05:37 UTC, Eryngii01 commented on Assets/Code/Scripts/Heroes/BehaviourTree/Decorators/Repeater.cs
> +using System.Collections;
Hm...I hadn't implemented that one yet and adding anymore would be make the PR even bigger, so I'll delete the file for now and keep the task on Trello so I can remember to come back to it in the next `Hero AI` update 👍

2023-11-18 05:44 UTC, Eryngii01 commented on Assets/Code/Scripts/Heroes/FieldOfView.cs
> +            Gizmos.matrix = Handles.matrix = transform.localToWorldMatrix;
Thank you for pointing that out and relieving me of the terror that could have been 😆 
I'll keep that in mind for the future 👍 

Fixed!

2023-11-18 05:46 UTC, Eryngii01 commented on Assets/Code/Scripts/Heroes/AI/Basic/Checks/DecideJumpForce.cs
> +                Debug.LogError("Hero cannot find a target platform!");
That's a fair point; I hadn't put too much thought into the urgency level when including that... 😅 

I'll switch it to a `Warning` 👍

2023-11-18 05:49 UTC, Eryngii01 commented on Assets/Prefabs/Traps/TestTrap1.prefab
I was thinking the same thing 👍 
Maybe we can address this in a really quick PR once this and the `UI Update` are taken care of 👌

2023-11-18 06:02 UTC, Eryngii01 commented on Assets/Code/Scripts/Heroes/AI/Basic/Checks/DecideJumpForce.cs
> +                Debug.LogError("Hero cannot find a target platform!");
Fixed!

2023-11-18 06:05 UTC, Eryngii01 commented on Assets/Code/Scripts/Heroes/BehaviourTree/Decorators/Repeater.cs
> +using System.Collections;
Fixed!

2023-11-18 06:06 UTC, Eryngii01 commented on Assets/Prefabs/Traps/TestTrap1.prefab
I'll make a ticket for this 👌

2023-11-18 06:16 UTC, Eryngii01 commented on Assets/Code/Scripts/Heroes/AI/Basic/Tasks/ApproachTarget.cs
> +                case true when isHeroOnPlatform:
Me neither really, Rider helped make the suggestion for me which I'll keep for the notes from now on! 🔥 😆

2023-11-18 07:19 UTC, eon704 commented on Assets/Prefabs/Traps/TestTrap1.prefab
Yeah, we have a decent number of files that are outdated and are no longer used. A dedicated PR for cleanup sounds great!

2023-11-18 07:21 UTC, eon704 approved these changes
LGTM! 🔥

2023-11-18 07:37 UTC, merged