UI Update
KrillOrBeKrilled/GMTK-2023 pull request #41
Opened 2023-11-15 07:25 UTC by eon704

## Changes:
- Updated UI throughout the game with new Sprites.
- Updated `UIButton` to change sprites when pressed to _highlighted_ version of the sprite.
- Added `UIHoldButton` to trigger an action once it's held for the required duration.
- Added `EventManager` to manage all event subscriptions and invokes.
  - Not used fully yet, existing code will need to be migrated later.

## Screenshots and Videos:

### Main Menu
![Menu](https://github.com/KrillOrBeKrilled/GMTK-2023/assets/16372290/9597dd58-1ef8-4b08-b62a-a7837d7f5707)

### Levels
![Levels](https://github.com/KrillOrBeKrilled/GMTK-2023/assets/16372290/369fb4af-baeb-4c3e-8770-a9906eba8448)

### Game
![Game](https://github.com/KrillOrBeKrilled/GMTK-2023/assets/16372290/414a31d2-3f1f-4187-a5b8-8b1a8cf9d6ae)

![NewWin](https://github.com/KrillOrBeKrilled/GMTK-2023/assets/16372290/6105db9f-9f03-4572-bf89-fbcdf12af682)

![NewNewLoss](https://github.com/KrillOrBeKrilled/GMTK-2023/assets/16372290/585a915a-5958-4f00-8b9f-ca70bc287502)

https://github.com/KrillOrBeKrilled/GMTK-2023/assets/16372290/75f27ad7-bbf9-4352-81b0-dceb54d643d6

2023-11-16 04:45 UTC, Eryngii01 commented on Assets/Code/Scripts/UI/TrapRequirementsUI.cs
> +  public class TrapRequirementsUI : MonoBehaviour {
The name `TrapRequirementsUI` is really close to `TrapRequirementUI` and might be confusing. I would suggest going with something like `TrapRequirementListUI` (though there's a chance it might also be confused with a List, but also provides some self-explanatory-ness) or `TrapRequirementInfoUI`

2023-11-16 05:07 UTC, Eryngii01 commented on Assets/Code/Scripts/UI/UIButton.cs
> +        /// <summary> Invokes the <see cref="_onClickImmediate"/> and <see cref="_onClickComplete"/> events. </summary>
`_onClickImmediate` is not invoked in `OnPointerUp`. Is this intentional?

2023-11-17 02:03 UTC, Eryngii01 requested changes
The new UI looks great; the aesthetic fits and is consistent, and the elements are well-placed in respect to each other. I especially like the responsivity of the elements! Overall, everything looks good.

There is one issue I found during playtesting while the rest are mere suggestions:
⭐ If any button is held while the pause menu is active, the game will automatically resume without closing the window, so it's possible to lose while paused

https://github.com/KrillOrBeKrilled/GMTK-2023/assets/66287115/e8f500ad-e465-40fb-b993-c09e9b39a384

- I personally find the tween when selecting a different trap on the trap toolbar to be a bit overstimulating. I think the tween makes sense for just opening and closing the trap info window.

https://github.com/KrillOrBeKrilled/GMTK-2023/assets/66287115/e949ec3a-e9c4-495f-aefc-04c2d3a8a688

- When I stare at the trap toolbar while moving, the scenery movement behind the panel can be a little trippy to look at...Turning up the opacity enough might make it less noticeable.
- The resources UI overlaps the movement input stick, so we may want to move this UI element more to the left.
- If it's possible in a future PR, it would be very user-friendly to allow the player to unselect a button if they drag their finger off the button after pressing and holding it. Sometimes we change our minds or make mistakes! 😄 

After the pause menu fix and the adjustment to the class name in an earlier comment, this PR is good to go!

2023-11-17 09:02 UTC, eon704 commented
Thank you for taking a look! Will how to address the requested changes and re-request review after that 👌

2023-11-18 07:34 UTC, eon704 commented on Assets/Code/Scripts/UI/TrapRequirementsUI.cs
> +  public class TrapRequirementsUI : MonoBehaviour {
Renamed `TrapRequirementUI` to `ResourceRequirementUI`, since it's not really related to the `Trap`.
Also happens to be how I have already named `GameObjects` containing the script in the scene

2023-11-18 07:59 UTC, eon704 commented on Assets/Code/Scripts/UI/UIButton.cs
> +        /// <summary> Invokes the <see cref="_onClickImmediate"/> and <see cref="_onClickComplete"/> events. </summary>
Updated `summary` 👌 
Going to update for the press and drag-off-the-button to not trigger button

2023-11-18 08:14 UTC, eon704 commented on Assets/Code/Scripts/UI/UIButton.cs
> +        /// <summary> Invokes the <see cref="_onClickImmediate"/> and <see cref="_onClickComplete"/> events. </summary>
Hmm, after some research on Unity's built-in `OnScreenButton` component that connects to the Input System, it appears that it triggers as soon as it is pressed.

I believe there is a way to write a custom button or extend the existing `UIButton` to only trigger once a pointer/finger is lifted. I am leaning toward adding that in a separate PR as it will require a good amount of events to be re-assigned in Unity for buttons.

2023-11-19 19:30 UTC, eon704 commented
## Changes:
- Bounce tween of trap requirements when selecting a new trap removed. Bounce only on appearing now.
- Trap requirements now resizes to fit all types of resources.
- Updated UI Placement.
- Drag-off-the-button to cancel added.
- PauseUI fixed.
- Panels on UI backgrounds made opaque.

2023-11-20 02:35 UTC, Eryngii01 approved these changes
- Bounce tween of trap requirements when selecting a new trap removed. Bounce only on appearing now.
-> Works perfectly!
- Trap requirements now resizes to fit all types of resources.
-> It looks and works very well! Thank you!
- Updated UI Placement.
-> The new UI design works really well for toggling the trap recipe UI easily 🎉 
-> However, now that the resource count overlaps the resource images, I realize on a smaller screen that I rely more on color to distinguish the number and the solid white color is harder to read next to other bright colors like the ones in the slime sprite. Maybe we could change the color to something slightly different, swap the outline and solid colors, or make a tiny UI backsplash to help distinguish them?
![UI example](https://github.com/KrillOrBeKrilled/GMTK-2023/assets/66287115/98d1f563-2f0f-4aef-96b8-7077ba5d669d)

Maybe something like a little bubble like this? (minus the energy thing) Although I'm not sure how much that would fit with the art style...
- Drag-off-the-button to cancel added.
-> Thank you for adding this in! 🙏 It works well although if you don't mind me being picky, is there a way to change the highlighted hover image back to the un-highlighted image for the button in response to when the finger swipes off it? This isn't terribly necessary, but I think it would be a nice addition!
- PauseUI fixed.
-> Works well!
- Panels on UI backgrounds made opaque.
-> It looks great!

2023-11-20 03:04 UTC, merged