Trap resources
KrillOrBeKrilled/GMTK-2023 pull request #49
Opened 2023-12-07 00:05 UTC by Kevin22888

Three major updates: dependencies, resource manager, and resource spawner.

Dependencies:
- Namespace `Managers` now depends on `Traps` and `Heroes`.
- When a trap is constructed, `TrapController` is now responsible for using `TilemapManager` to set tilemaps. Thus the `TilePosition` variable passed into `Trap`’s `Construct()` method may be redundant.
- `CoinManager` is currently removed from `Hero` to remove the dependency to that entire namespace. Coin collection logic will need another update.

ResourceManager:
- Uses a dictionary for the player inventory, where a `ResourceType` is mapped to an integer amount.
- Methods: `AddResource`, `ConsumeResources`, `CanAffordCost`. The basic operations to manage the player inventory.
- ***`AddResource` is subscribed to a static Action delegate `OnResourceCollected`, located in `ResourcePickup` in `Traps` namespace.***
- Also uses `EventManager` to broadcast a `ResourceAmountChangedEvent` to the `GameUI`.
In the UI namespace, added a `ResourceUI` to update the inventory bar at the top right corner of the screen.
- For each `Trap` class, the cost has been changed to a dictionary recipe. We use a `RecipeEntry` serializable to enable easy changes using the Editor, but the actual dictionary for the recipe is `_recipe`. 
- This `_recipe` cannot be initialized through Awake or Start, because the object isn’t activated in the scene. So right now we are using lazy-loading with a public `Recipe` property, but this could become an overhead in the long run. Perhaps try a Scriptable Object for the recipes.

ResourceSpawner:
- Spawns the resource pickup gameObjects into the game. 
- There are two types of drops. 
- (1) Level Drop: native to the level itself, spawned randomly in a region in front of the player (towards the right)
- (2) Hero Drop: specific to each hero type, spawned at the position where the hero dies.
- Includes a `ResourceDrop` serializable which contains the type, actual pickup prefab, and a weight for the drop rate.
- Uses a list of `ResourceDrop` for the level drops, and a dictionary to map each hero type to a list of `ResourceDrop`.
- Methods are all private, with the main logic in `SpawnLevelDrop`, `SpawnHeroDrop`, and `GetRandomDrop`.
- `GetRandomDrop` chooses an item from the list of `ResourceDrop` according to their weights.
- ***`SpawnHeroDrop` is subscribed to a static Action delegate `OnHeroDeath`, located in the `Hero` class.***

Further updates:
- ***Currently, the two static Action delegates mentioned above are used to get around dependency problems. Need to be refactored later.***
- A new layer, `Pickups`, is added. Unchecked the `Pickups` and `Heroes` interactions in Physics 2D Layer Collision Matrix.

Some known issues & side effects:
- Resource drops may spawn on top of the pit and fall into it (could be kept as intentional or changed to be easier on the player).
- When hero drops resources due to falling down the pit, the drops can pile up and get stuck there.
- ***Resource drops may spawn directly on an `IcicleTrap` instance, causing the icicle to fall down.***
- `IclcleTrap` bugs are not fixed yet.

2023-12-07 06:34 UTC, Eryngii01 commented on Assets/Code/Scripts/Managers/ResourceManager.cs
> +                EventManager.Instance.ResourceAmountChangedEvent.Invoke(cost.Key, _inventory[cost.Key]);
This isn't too much of a problem for now, but if we expand the inventory system a lot more, the event will be invoked for each resource type, which can add up over time in great numbers (say, if we have >20 unique types). I would suggest batching the updated key-value pairs that have been changed through a new dictionary, list of tuples, data structure of choice, etc. and then invoke the `ResourceAmountChangedEvent` once at the end. Then `ResourceUI.SetAmount` can parse through the data and update each icon amount on its own.

2023-12-07 19:42 UTC, Kevin22888 commented on Assets/Code/Scripts/Managers/ResourceManager.cs
> +                EventManager.Instance.ResourceAmountChangedEvent.Invoke(cost.Key, _inventory[cost.Key]);
Yeah that's a good point! This can also shorten the code for the `DelayInventoryInit` method, we can just populate the inventory and notify the listeners only once

2023-12-08 04:22 UTC, Eryngii01 commented on Assets/Code/Scripts/Managers/ResourceManager.cs
> +                _inventory.Add(type, 0);
If it's decided to batch the changed inventory types, we can set the default values to 5 here and then invoke `ResourceAmountChangedEvent` to completely omit the second loop

2023-12-08 04:54 UTC, Eryngii01 commented on Assets/Code/Scripts/Managers/ResourceSpawner.cs
> +            if (!_dropMap.ContainsKey(heroType)) return;
This check could also double as a means to log a warning to any of us developers if the properties for `_heroDrops` were not set properly in the editor. It would be really helpful, especially since it's easy to forget that something is set and fishing for bugs takes time without a helpful hint! 😄

2023-12-08 05:16 UTC, Eryngii01 commented on Assets/Code/Scripts/Managers/ResourceSpawner.cs
> +            if (pickup.Rigidbody2D != null) {
This is a nitpick, but it may be a good idea to keep the `Rigidbody2D` of the `ResourcePickup` private and only accessible to itself and then have `ApplyInitialForces` call some exposed method from `ResourcePickup` that takes care of this work itself.

2023-12-08 05:19 UTC, Eryngii01 commented on Assets/Code/Scripts/Managers/TilemapManager.cs
> +            if (this._trapTileMap == null) return;
This is another case that gives rise to logging a warning to help with potential debugging! Any of the comments about logging warnings though can always be saved for another PR in the future! 😄

2023-12-08 05:43 UTC, Eryngii01 requested changes
Great work on the new material system! It's really fun to work with and definitely adds some new flavor to the gameplay loop!

I did run into some playtest bugs that may need to be addressed before this feature can be finalized:
- The materials themselves have some force to them as they fall (the ones spawned for the level) that can affect the player's movement. There are no issues when collecting pickups from the side.
-> One scenario is when the player is below the falling material but slightly at an angle (not directly below). I noticed that when the material falls at a faster velocity, the player object was pushed ever so slightly in away from it. This isn't too big of a deal normally, but for situations that are extremely dire (such as when a hero gets really close to the player), the slightest movement can make or break the situation
-> When the player is directly below a falling pickup and jumps up towards it, the velocity of the falling pickup is enough to overcome the player's jump velocity, thus ending the player's jump state prematurely and proceeding to glide. I haven't yet fallen into a pit yet due to this, but it may be possible to cut it really close when this occurs.
- The resources will spawn during dialogue sequences, so players can potentially game the system by leaving the game running to accumulate the pickups before starting the level.
- The bounciness of the pickups is satisfying, but it does cause them to bounce off each other and down the platform pits, which can be slightly frustrating in certain circumstances.

Along with fixes to some of the previous comments to update the `ResourceManager` and `ResourceSpawner`, this should be good to go!

Overall solid work, and I look forward to further developing this feature into other gameplay systems in the future!

2023-12-08 14:16 UTC, Kevin22888 commented on Assets/Code/Scripts/Managers/TilemapManager.cs
> +            if (this._trapTileMap == null) return;
For this one, we actually need some extra changes. I intentionally put this check here to stop the null error when a level ends, because it will always be null when a level ends. 

The reason is that after I changed the Traps and Managers dependency, the TrapController uses this TilemapManager method to reset tiles. This method is subscribed to an `_onDestroyed` event in `Trap`, when a trap is destroyed that's when we reset the tiles, but when the level ends and both the traps and tilemaps are destroyed, this method gets called again and tries to reset the null tilemaps, that's why I put this here to explicitly prevent that.

For now I'll keep the debug message, when we see this message again (probably every time we restart a level haha) that'll work as another reminder to fix this issue

2023-12-09 00:24 UTC, Eryngii01 commented
The fixes work well, and the updates to allow more elements to be customizable work great!

Just to recap so that I don't forget these tickets to be made in the future; these don't need to be addressed asap:
1. The hen jump is still thwarted prematurely when jumping to a pickup falling directly above the player, but this isn't a terribly game-breaking issue and can be solved in a future PR.
2. Object pooling can implemented for the pickups.
3. Pickups can spawn and push the icicle traps around.

Overall great work!

2023-12-09 00:24 UTC, Eryngii01 approved these changes
LGTM!

2023-12-09 01:16 UTC, merged