Level layout moved to LevelData
KrillOrBeKrilled/GMTK-2023 pull request #83
Opened 2024-03-23 05:13 UTC by eon704

## Changes:
- Moved to the `LevelData`:
  - Tilemap Walls .
  - Camera bounds.

- Multiple levels scenes are merged into Game scene.
- Trap Tilemap is painted automatically on level start.
- Cleaned up no longer used scenes.
- Cleared sorting layers on pickup prefabs.
- Other minor changes.

2024-03-23 05:36 UTC, Eryngii01 requested changes
Test Utility Tool

2024-03-23 20:44 UTC, Eryngii01 commented on Assets/Code/Scripts/Core/Managers/GameManager.cs
> +            LevelData sourceData = _testingLevelData != null ? _testingLevelData : LevelManager.Instance.GetActiveLevelData();
Thank you for including this addition! It'll greatly help cut the time taken to do extensive testing for level scenes!

2024-03-23 21:03 UTC, Eryngii01 commented on Assets/Code/Scripts/UI/LevelsUI.cs
> +            this._screenWipe.WipeIn(() => this.LoadLevelScene(levelName));
Thank you for the ugly code fix 🙏

2024-03-24 01:37 UTC, eon704 commented
This update has broken the cameras in the Vertical Camera test scene. I didn't touch the scene for now, I think we can fix that I  a later PR once we try to include those features in the level design

2024-03-24 21:37 UTC, Eryngii01 approved these changes
LGTM!

2024-03-24 22:13 UTC, merged